In [14]:
import pandas as pd
import numpy as np
df=pd.read_csv('C:/Users/Anjal/Downloads/CFPB.csv')
df.head()

Date received                                            Product  \
0      01/03/23  Credit reporting, credit repair services, or o...   
1      01/03/23  Credit reporting, credit repair services, or o...   
2      01/18/23  Credit reporting, credit repair services, or o...   
3      01/03/23  Credit reporting, credit repair services, or o...   
4      01/03/23  Credit reporting, credit repair services, or o...   

        Sub-product                                              Issue  \
0  Credit reporting  Problem with a credit reporting company's inve...   
1  Credit reporting               Incorrect information on your report   
2  Credit reporting  Problem with a credit reporting company's inve...   
3  Credit reporting  Problem with a credit reporting company's inve...   
4  Credit reporting  Problem with a credit reporting company's inve...   

                                           Sub-issue  \
0  Their investigation did not fix an error on yo...   
1                Information belongs to someone else   
2  Their investigation did not fix an error on yo...   
3               Investigation took more than 30 days   
4  Their investigation did not fix an error on yo...   

                        Consumer complaint narrative  \
0  Why do you continue to ignore my request to bl...   
1  This is my fourth endeavor to tell you that I ...   
2                                                NaN   
3  Despite the multiple previous written requests...   
4                                                NaN   

                             Company public response  \
0                                               None   
1                                               None   
2  Company has responded to the consumer and the ...   
3  Company has responded to the consumer and the ...   
4  Company has responded to the consumer and the ...   

                                  Company State ZIP code  Tags  \
0                           EQUIFAX, INC.    WA    98404  None   
1                           EQUIFAX, INC.    MD    20746  None   
2     Experian Information Solutions Inc.    CA    90744  None   
3  TRANSUNION INTERMEDIATE HOLDINGS, INC.    CA    92677  None   
4  TRANSUNION INTERMEDIATE HOLDINGS, INC.    MD    21117  None   

  Consumer consent provided? Submitted via Date sent to company  \
0           Consent provided           Web             01/03/23   
1           Consent provided           Web             01/03/23   
2       Consent not provided           Web             01/25/23   
3           Consent provided           Web             01/03/23   
4                      Other           Web             01/03/23   

      Company response to consumer Timely response?  Consumer disputed?  \
0          Closed with explanation              Yes                 NaN   
1          Closed with explanation              Yes                 NaN   
2          Closed with explanation              Yes                 NaN   
3  Closed with non-monetary relief              Yes                 NaN   
4  Closed with non-monetary relief              Yes                 NaN   

   Complaint ID  
0       6386683  
1       6386679  
2       6455050  
3       6386662  
4       6386692

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90449 entries, 0 to 90448
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Date received                 90449 non-null  object 
 1   Product                       90449 non-null  object 
 2   Sub-product                   90449 non-null  object 
 3   Issue                         90449 non-null  object 
 4   Sub-issue                     90449 non-null  object 
 5   Consumer complaint narrative  37891 non-null  object 
 6   Company public response       90449 non-null  object 
 7   Company                       90449 non-null  object 
 8   State                         90449 non-null  object 
 9   ZIP code                      90449 non-null  object 
 10  Tags                          90449 non-null  object 
 11  Consumer consent provided?    87258 non-null  object 
 12  Submitted via                 90449 non-null  object 
 13  D

In [16]:
df=df[['Product',
       'Sub-product',
       'Issue',
       'Sub-issue',
       'Consumer complaint narrative',
       'Company public response',
       'Company',
       'Consumer consent provided?',
       'Timely response?']]

In [17]:
df.describe()

Product       Sub-product  \
count                                               90449             90449   
unique                                                  9                48   
top     Credit reporting, credit repair services, or o...  Credit reporting   
freq                                                69759             69210   

                              Issue  \
count                         90449   
unique                           77   
top     Improper use of your report   
freq                          25946   

                                            Sub-issue  \
count                                           90449   
unique                                            156   
top     Reporting company used your report improperly   
freq                                            19702   

                             Consumer complaint narrative  \
count                                               37891   
unique                                              30816   
top     I'm really not sure what happened. I have mail...   
freq                                                  186   

                                  Company public response  \
count                                               90449   
unique                                                 10   
top     Company has responded to the consumer and the ...   
freq                                                51752   

                                       Company Consumer consent provided?  \
count                                    90449                      87258   
unique                                    1379                          5   
top     TRANSUNION INTERMEDIATE HOLDINGS, INC.       Consent not provided   
freq                                     21846                      45896   

       Timely response?  
count             90449  
unique                2  
top                 Yes  
freq              89928

In [18]:
df['Product'].value_counts()

Credit reporting, credit repair services, or other personal consumer reports    69759
Debt collection                                                                  5417
Checking or savings account                                                      4938
Credit card or prepaid card                                                      4244
Mortgage                                                                         2404
Vehicle loan or lease                                                            1295
Money transfer, virtual currency, or money service                               1232
Student loan                                                                      589
Payday loan, title loan, or personal loan                                         571
Name: Product, dtype: int64

In [19]:
df['Sub-product'].value_counts()

Credit reporting                              69210
Checking account                               4145
General-purpose credit card or charge card     3353
Other debt                                     1643
I do not know                                  1426
Conventional home mortgage                     1390
Loan                                           1159
Credit card debt                               1130
Medical debt                                    762
Store credit card                               527
FHA mortgage                                    488
Federal student loan servicing                  458
Other personal consumer report                  407
Mobile or digital wallet                        405
Savings account                                 385
Domestic (US) money transfer                    383
Other banking product or service                329
Installment loan                                271
Auto debt                                       249
VA mortgage 

In [20]:
df['Issue'].value_counts().head(10)

Improper use of your report                                                         25946
Incorrect information on your report                                                24979
Problem with a credit reporting company's investigation into an existing problem    18290
Attempts to collect debt not owed                                                    3017
Managing an account                                                                  2906
Problem with a purchase shown on your statement                                      1085
Trouble during payment process                                                       1080
Written notification about debt                                                       929
Struggling to pay mortgage                                                            799
Getting a credit card                                                                 646
Name: Issue, dtype: int64

In [21]:
df['Company'].value_counts().head(10)

TRANSUNION INTERMEDIATE HOLDINGS, INC.    21846
EQUIFAX, INC.                             21508
Experian Information Solutions Inc.       21086
WELLS FARGO & COMPANY                      3283
CAPITAL ONE FINANCIAL CORPORATION          1313
BANK OF AMERICA, NATIONAL ASSOCIATION      1174
JPMORGAN CHASE & CO.                       1163
CITIBANK, N.A.                              785
Bread Financial Holdings, Inc.              664
SYNCHRONY FINANCIAL                         585
Name: Company, dtype: int64

In [22]:
df.dropna(subset=['Consumer complaint narrative'], inplace=True)


In [23]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline 
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB, ComplementNB

In [24]:
x=df['Consumer complaint narrative']
y=df['Product']

In [25]:
print(x)


0        Why do you continue to ignore my request to bl...
1        This is my fourth endeavor to tell you that I ...
3        Despite the multiple previous written requests...
5        I have been receiving phone calls from debt co...
6        I have disputed the referenced accounts to the...
                               ...                        
90393    In accordance with the Fair Credit Reporting a...
90396    Hello, I have received numerous calls from the...
90414    Date : XX/XX/2022 Amount : XXXX Account Status...
90436    Helper in need of help! \nHello, I am in dire ...
90446    Last year I got a solar system for my house th...
Name: Consumer complaint narrative, Length: 37891, dtype: object


In [26]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=.2,random_state=42)

In [27]:
Y_train


54596    Credit reporting, credit repair services, or o...
10039    Credit reporting, credit repair services, or o...
59876    Credit reporting, credit repair services, or o...
46332                                      Debt collection
454                            Checking or savings account
                               ...                        
33154    Credit reporting, credit repair services, or o...
11261    Credit reporting, credit repair services, or o...
22017                                         Student loan
1435     Credit reporting, credit repair services, or o...
31084                          Credit card or prepaid card
Name: Product, Length: 30312, dtype: object

In [28]:
pipe_svc=Pipeline([('tfidf',TfidfVectorizer(stop_words='english',ngram_range=(1,3))),
                  ('clf',LinearSVC())])
pipe_CNB=Pipeline([('tfidf',TfidfVectorizer(stop_words='english',ngram_range=(1,3))),
                  ('clf',ComplementNB())])
pipe_MNB=Pipeline([('tfidf',TfidfVectorizer(stop_words='english',ngram_range=(1,3))),
                  ('clf',MultinomialNB())])

In [29]:
model_svc=pipe_svc.fit(X_train,Y_train)
model_CNB=pipe_CNB.fit(X_train,Y_train)
model_MNB=pipe_MNB.fit(X_train,Y_train)

In [30]:
predict_svc=model_svc.predict(X_test)
predict_CNB=model_CNB.predict(X_test)
predict_MNB=model_MNB.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,classification_report
Acc_scv=accuracy_score(Y_test,predict_svc)
Acc_CNB=accuracy_score(Y_test,predict_CNB)
Acc_MNB=accuracy_score(Y_test,predict_MNB)
print(Acc_scv)
print(Acc_CNB)
print(Acc_MNB)

0.9242644148304525
0.762765536350442
0.7049742710120068


In [32]:
text='I dont have money to pay my loan which i have taken for my car '
model_svc.predict([text])


array(['Vehicle loan or lease'], dtype=object)

In [33]:
print(classification_report(Y_test,predict_svc))

                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.81      0.89      0.85       569
                                                 Credit card or prepaid card       0.83      0.78      0.80       515
Credit reporting, credit repair services, or other personal consumer reports       0.96      0.98      0.97      5274
                                                             Debt collection       0.85      0.78      0.81       507
                          Money transfer, virtual currency, or money service       0.83      0.47      0.60       142
                                                                    Mortgage       0.89      0.91      0.90       266
                                   Payday loan, title loan, or personal loan       0.70      0.30      0.42        77
                                                       

In [36]:
from sklearn.metrics import confusion_matrix

# Example: Confusion matrix for LinearSVC model
conf_matrix_svc = confusion_matrix(Y_test, predict_svc)
print("Confusion Matrix - LinearSVC:")
print(conf_matrix_svc)


Confusion Matrix - LinearSVC:
[[ 508   29   13    4    7    4    0    0    4]
 [  38  402   60    5    6    2    1    0    1]
 [   9   24 5191   39    0    3    3    2    3]
 [   1    6   84  396    1    5    2    1   11]
 [  55    6    7    2   67    3    1    0    1]
 [   6    3    9    4    0  242    0    0    2]
 [   9    9   16    9    0    5   23    0    6]
 [   1    2    6    4    0    1    0   57    1]
 [   1    6   15    5    0    8    3    0  119]]


In [38]:
from sklearn.ensemble import VotingClassifier

# Example: Ensemble method with LinearSVC, ComplementNB, and MultinomialNB
ensemble_model = VotingClassifier([('svc', pipe_svc), ('cnb', pipe_CNB), ('mnb', pipe_MNB)], voting='hard')
ensemble_model.fit(X_train, Y_train)
predict_ensemble = ensemble_model.predict(X_test)
print("Classification Report - Ensemble:")
print(classification_report(Y_test, predict_ensemble))

Classification Report - Ensemble:
                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.84      0.47      0.60       569
                                                 Credit card or prepaid card       0.95      0.13      0.23       515
Credit reporting, credit repair services, or other personal consumer reports       0.75      1.00      0.86      5274
                                                             Debt collection       0.97      0.12      0.21       507
                          Money transfer, virtual currency, or money service       0.92      0.08      0.15       142
                                                                    Mortgage       0.95      0.30      0.45       266
                                   Payday loan, title loan, or personal loan       1.00      0.01      0.03        77
                     